#!/bin/bash

# low battery in %
LOW_BATTERY="7"
# critical battery in % (execute action)
CRITICAL_BATTERY="2"
# action
ACTION="/usr/sbin/pm-suspend"
# display icon
ICON="/home/taras/.scripts/icons/low_battery.png"
# path to battery /sys
BATTERY_PATH="/sys/class/power_supply/BAT0/"


if [ -e "$BATTERY_PATH" ]; then
    BATTERY_ON=$(cat $BATTERY_PATH/status)

    if [ "$BATTERY_ON" == "Discharging" ]; then
        CURRENT_BATTERY=$(cat $BATTERY_PATH/capacity)

        if [ "$CURRENT_BATTERY" -lt "$CRITICAL_BATTERY" ]; then
            $($ACTION)
        elif [ "$CURRENT_BATTERY" -lt "$LOW_BATTERY" ]; then
            export DISPLAY=:0
            notify-send -i "$ICON"  "Battery IS LOW - $CURRENT_BATTERY %"
        fi
    fi
fi
