#!/bin/bash

filename=$(basename "${1}")

find * -maxdepth 0 -type f -iname "*.jpg" -or -iname "*.png" -or -iname "*.bmp" -or -iname "*.thm" -or -iname "*.chk" | \
sed ':a;N;/\n'"${filename}"'/!{ba;};h;s;^.*\n;;;x;s;\n[^\n]*$;\n;;x;:s;$!{N;bs};G;' | \
sed -e 's/\ /\\ /g' -e 's/\[/\\[/g' -e 's/\]/\\]/g' > /tmp/fehlist

cat /tmp/fehlist | xargs feh -q -F --hide-pointer
